[package]
name = "advent-of-code-template"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.12", features = ["derive"] }
clap-verbosity-flag = "2.1.1"
env_logger = "0.10.1"
log = "0.4.20"
strum = "0.25.0"
strum_macros = "0.25.3"